### ISSUE TITLE
Error when initializaing blizz_auth()

### ISSUE THREAD

**Issue by rubengmoran** [tyluRp/blizz#1]
R returns an error when introducing credentials:

"Error in utils::read.table(renv, stringsAsFactors = FALSE) : 
  no lines available in input"

I'm pretty sure this is due to renv file being empty from the very beginning, the script stops running and there's nothing you can do.

I've tried debugging the blizz_auth.R and it can work with a try statement. However the script does nothing at the end since there's no URL to be connected with in blizz_auth.R. script...

**Comment by tylerlittlefield** [comment]
@rubengmoran I haven't maintained this package in over 2 years, I sort of abandoned it to be honest. I will take a look at it later though and see if I can get things working. Thanks.

**Comment by rubengmoran** [comment]
That was a quick response! Appreciated.

I suspect that "utils.R" isn't being executed in the package or included somehow. I've ran utils.R in my machine and it effectively returns the token, just in case this can help with the bug!

Thanks

**Comment by tylerlittlefield** [comment]
@rubengmoran Thanks for being patient. You were spot on, `blizz_auth()` was having trouble with an empty `.Rprofile`. I've wrapped it in a `tryCatch` to resolve. Try installing the development branch and see if it works for you:
```r
devtools::install_github("tylurp/blizz", ref = "dev")
```
Below is an example query I just ran (yay, the API hasn't changed!):
```r
library(blizz)
library(tibble)

as_tibble(blizz("/sc2/ladder/grandmaster/1"))
#> ✓ Request: https://us.api.blizzard.com/sc2/ladder/grandmaster/1
#> ✓ Status: 200
#> ✓ Content-Type: application/json; charset=utf-8
#> # A tibble: 161 x 1
#>    ladderTeams$teamM… $previousRank $points  $wins  $losses $mmr  $joinTimestamp
#>    <list>             <list>        <list>   <list> <list>  <lis> <list>        
#>  1 <df[,6] [1 × 6]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  2 <df[,6] [1 × 6]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  3 <df[,6] [1 × 6]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  4 <df[,5] [1 × 5]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  5 <df[,5] [1 × 5]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  6 <df[,5] [1 × 5]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  7 <df[,6] [1 × 6]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  8 <df[,5] [1 × 5]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#>  9 <df[,5] [1 × 5]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#> 10 <df[,5] [1 × 5]>   <int [1]>     <int [1… <int … <int [… <int… <int [1]>     
#> # … with 151 more rows
```
As a side note, the development branch doesn't refresh the authentication token on load anymore using `blizz_auth(refresh=TRUE)`. I had some weird errors trying to install because of this, so I need to rethink the `.onLoad` behavior and perhaps force the user to do this themselves when the token expires, something like warning so the user knows they need to refresh.

**Comment by tylerlittlefield** [comment]
Another side note: I never spent much time parsing the response of these requests, so some manipulation of the data is needed if you want it in a tidy format. I might spend time on this in the future if there is interest. Below is an example of what I am talking about:
```r
library(blizz)
library(dplyr)
library(tidyr)

blizz("/sc2/ladder/grandmaster/1") %>% 
  .[["ladderTeams"]] %>% 
  as_tibble() %>% 
  unnest(cols = c(
    teamMembers,
    previousRank,
    points,
    wins,
    losses,
    mmr,
    joinTimestamp
  )) %>% 
  unnest(cols = c(
    id,
    realm,
    region,
    displayName,
    clanTag,
    favoriteRace
  ))
#> ✓ Request: https://us.api.blizzard.com/sc2/ladder/grandmaster/1
#> ✓ Status: 200
#> ✓ Content-Type: application/json; charset=utf-8
#> # A tibble: 161 x 12
#>    id    realm region displayName clanTag favoriteRace previousRank points  wins
#>    <chr> <int>  <int> <chr>       <chr>   <chr>               <int>  <int> <int>
#>  1 4318…     1      1 Namshar     PSISTM  zerg                    0   1786    67
#>  2 2553…     1      1 Nina        Ex0n    protoss                 3   3808   619
#>  3 6685…     2      1 Cham        Ex0n    zerg                    3   3339   364
#>  4 8471…     1      1 PureLegacy  <NA>    terran                  6   3417   321
#>  5 9641…     1      1 IIIIIIIIII… <NA>    protoss                70   2617    91
#>  6 4716…     1      1 IIlIIIIIIl… <NA>    zerg                    3   3525   300
#>  7 3271…     1      1 Epic        PSISTM  terran                  0    361     9
#>  8 4816…     1      1 PiLiPiLi    <NA>    protoss                 8   3630   591
#>  9 8319…     1      1 YeezyforPr… <NA>    terran                  4   3480   176
#> 10 1079…     1      1 FireBooty   <NA>    terran                  0    169     5
#> # … with 151 more rows, and 3 more variables: losses <int>, mmr <int>,
#> #   joinTimestamp <int>
```

**Comment by rubengmoran** [comment]
Hey! Thanks for your answer. While the error won't show up again once the tryCatch is implemented, the problem I commented  in my second post is still up. 

When I try to authenticate thru blizz_auth("xxxx","yyyyy") nothing happens since there's no URL to be connected! From what I see, this connection needs to rely in "utils.R" but it's not being called in any part of blizz_auth/blizz scripts. Inside blizz_auth.R there's no URL so it won't retrieve any token, which makes blizz.R break when it tries to connect thru this token.

See screenshot of what happens when I run blizz_auth + the query you posted:

![image](https://user-images.githubusercontent.com/71343853/93315231-15113780-f80b-11ea-9607-1b79c74a109a.png)

Thanks!

**Comment by rubengmoran** [comment]
Hey! Thanks for your answer. While the error won't show up again once the tryCatch is implemented, the problem I commented in my second post is still up.

When I try to authenticate thru blizz_auth("xxxx","yyyyy") nothing happens since there's no URL to be connected! From what I see, this connection needs to rely in "utils.R" but it's not being called in any part of blizz_auth/blizz scripts. Inside blizz_auth.R there's no URL so it won't retrieve any token, which makes blizz.R break when it tries to connect thru this token.

See screenshot of what happens when I run blizz_auth + the query you posted:


![image](https://user-images.githubusercontent.com/71343853/93315524-6e796680-f80b-11ea-9690-ce0b96bf4ce5.png)

**Comment by tylerlittlefield** [comment]
@rubengmoran Can you refresh your R session using: <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>F10</kbd>. The `.Rprofile` requires you to restart your session before anything takes effect. Here is what I did to test:

1. `usethis::edit_r_environ()` : deleted everything (stored a copy to restore my credentials), then saved and refreshed R session.
2. `blizz::blizz_auth(id, secret)` : then ran `blizz::blizz("/sc2/ladder/grandmaster/1")`, this will return the error you've shared above.
3. Restart R session and run `blizz::blizz("/sc2/ladder/grandmaster/1")`, this successfully returns data for me.

**Comment by rubengmoran** [comment]
That worked perfectly, I was far from the solution with the utils.R stuff hahaha

Thank you very much! Now I can play with wow data using R, which makes it very interesting. Just a question: everytime I run blizz_auth(id, secret) do I need to restart the session afterwards to make queries work? If yes, I'm curious why in case you have some time to explain :)

**Comment by tylerlittlefield** [comment]
Yay! Glad it's working. You shouldn't need to go through the authentication process anymore. However, you will need to refresh your token from time to time using:
```r
blizz::blizz_auth(refresh = TRUE)
```
Note that refreshing the token **doesn't** require you to refresh your R session because we set the environment variable for you, see [here](https://github.com/tyluRp/blizz/blob/dev/R/utils.R#L21).

On master branch, this is done every time you load the package so you can basically ignore authentication altogether. However, this was causing problems. I am thinking I might instead come up with a better way to run `blizz::blizz_auth(refresh=TRUE)` behind the scenes (without breaking things) so the user doesn't have to. For now, if a request fails, try refreshing the token and run again
